[package]
name = "don_mule"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
reqwest = { version = "0.12.15", features = ["blocking"] }
tokio = { version = "1.44.2", features = ["full"]}
